# -*- coding: utf-8 -*-
"""ejercicio29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_jwWGaf93It3fa7t4UfGYDGT3wDkdM0
"""

def validarm(monedas):
  for moneda in monedas:
    if moneda not in [5,10,50,100,200]:
      return False
  return True

def comprar(monedas, seleccionp):
  if not validarm(monedas):
    print('monedas no soportadas')
    return
  productos =[{"nombre":"papas fritas", "id":11,"precio":205},
              {"nombre":"chocolate","id":8,"precio":450},
              {"nombre":"galletas","id":6,"precio":50},
              {"nombre":"chiles","id":4,"precio":5}]
  switch = True
  precio_producto=0
  nombre_producto=""
  for p in productos:
    if seleccionp == p["id"]:
      precio_producto =p["precio"]
      nombre_producto=p["nombre"]
      switch = False
  if switch:
    print ('id de prod no existente')
    return
  pagot= sum(monedas)
  if pagot < precio_producto:
    print('trae dinero la sgte')
    return
  cambio=pagot-precio_producto
  print(cambio)
  print(nombre_producto)
  cambioarray=[]

  for corte in [5,10,50,100,200][::-1]:
    nro_rep_corte=cambio//corte
    if nro_rep_corte>0:
      aux_lista_cambio=[corte]*nro_rep_corte#nro de veces q se repite algo
      cambioarray.extend(aux_lista_cambio)#añadimos un elemento a un array
      cambio= cambio%corte
  print(cambioarray)

comprar([200,200,200],8)

comprar([200,100],11)